# Spatial GNN Configuration for Cardiomyocyte Differentiation Prediction

# Model Configuration
model:
  # Architecture
  input_dim: 2000  # Number of genes/features
  hidden_dims: [512, 256, 128]
  output_dim: 64
  num_classes: 10  # Number of cell types/states
  
  # GNN Configuration
  conv_type: 'GCN'  # Options: 'GCN', 'GAT', 'GraphConv'
  use_attention: false
  dropout: 0.1
  use_batch_norm: true
  
  # Multi-scale options
  use_multiscale: false
  scales: [3, 6, 12]

# Data Configuration
data:
  # Data paths
  data_dir: 'data'
  processed_file: 'processed_visium_heart.h5ad'
  
  # Preprocessing
  n_neighbors: 6  # For spatial graph construction
  n_top_genes: 2000
  normalize: true
  log_transform: true
  
  # Data splitting
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  
# Training Configuration
training:
  # Optimization
  learning_rate: 0.001
  weight_decay: 0.0001
  batch_size: 1  # Usually 1 for large graphs
  num_epochs: 100
  
  # Loss weights for multi-task learning
  classification_weight: 0.5
  regression_weight: 0.5
  
  # Scheduling and regularization
  scheduler_patience: 10
  scheduler_factor: 0.5
  early_stopping_patience: 20
  grad_clip_norm: 1.0
  
  # Checkpointing
  save_every: 10
  
# Experiment Configuration
experiment:
  name: 'spatial_gnn_cardiac'
  log_dir: 'experiments'
  seed: 42
  
# Hardware Configuration
hardware:
  device: 'auto'  # 'cuda', 'cpu', or 'auto'
  num_workers: 4
