advanced:
  attention_save_frequency: 50
  compute_embeddings: true
  embedding_dimensions:
  - 2
  - 3
  feature_importance: true
  gradient_analysis: true
  save_attention_maps: true
data:
  data_dir: data
  log_transform: true
  n_neighbors: 8
  n_top_genes: 3000
  normalize: true
  processed_file: processed_visium_heart.h5ad
  test_ratio: 0.15
  train_ratio: 0.7
  val_ratio: 0.15
experiment:
  log_dir: experiments_spatial
  name: enhanced_spatial_gnn_cardiac
  seed: 42
hardware:
  device: auto
  num_workers: 0
  pin_memory: true
model:
  conv_type: GAT
  dropout: 0.3
  hidden_dims:
  - 1024
  - 512
  - 256
  input_dim: 3000
  num_classes: 8
  num_heads: 8
  output_dim: 128
  scales:
  - 3
  - 6
  - 12
  - 24
  use_attention: true
  use_batch_norm: true
  use_multiscale: true
  use_residual: true
training:
  batch_size: 1
  classification_weight: 1.0
  early_stopping_patience: 30
  grad_clip_norm: 1.0
  learning_rate: 0.0005
  num_epochs: 200
  regression_weight: 0.5
  save_every: 25
  scheduler_factor: 0.7
  scheduler_patience: 15
  weight_decay: 0.0001
wandb:
  entity: null
  project: hybrid-gnn-rnn-cardiac-spatial
  tags:
  - spatial_gnn
  - cardiomyocyte
  - rtx5070ti
  - enhanced
